version: '3'

services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: always
    ports:
      - '1337:1337'
    environment:
      BASE_URL: 'https://planka-n66v.onrender.com' # Remplace par l'URL Render
      DATABASE_URL: 'postgres://planka:planka@db/planka'
      SECRET_KEY: '9c73f23dc5814f56ad731b1a7e63449965749b6317de4e14052f6ab1f6bf652b'
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: planka
      POSTGRES_PASSWORD: planka
      POSTGRES_DB: planka
